version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "aquila_super_user"
      MONGO_INITDB_ROOT_PASSWORD: "aquila_super_pwd@123"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local