spring:
  application:
    name : aquila-shipyard
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PWD}
      database: ${MONGO_DATABASE}
      authentication-database: admin